### ISSUE TITLE
[TRANSLATION REQUEST] - French (fr-FR) - Updated

### ISSUE THREAD

**Issue by AmoraMasFina** [OmarB97/trynano#17]
Here's an update to the French translation I recently provided : 
[fr-FR.txt](https://github.com/OmarB97/trynano/files/6195411/fr-FR.txt)

Also, please modify the language name, located in the language bar, as follows : from _France francaise_ to **Français (France)**.
This formulation is the most natural sounding to native speakers.

Thanks and keep up the good work :)

**Comment by OmarB97** [comment]
updated 🙂
