### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by VinickGold** [OmarB97/trynano#9]
I think would be nice to have a resource file for languages instead of relying on strings in the template file. This way other people could contribute with translations for the website. I know the browser can translate the site, but the default translation has a lot of erros at least in portuguese.

This way we could access "/pt-br , /fr ,  /es ,  /de" endpoints de to access specific language translations

**Comment by OmarB97** [comment]
Great suggestion, thanks!

**Comment by OmarB97** [comment]
I'll start looking into this one since it's very important for international usage. I'll try using this package: 

https://github.com/intlify/vue-i18n-next

**Comment by VinickGold** [comment]
Count on me to translate to portuguese if needed

**Comment by OmarB97** [comment]
@VinickGold added a PR for this 🙂

**Comment by VinickGold** [comment]
Added a PR with Portuguese translation, hope it helps.

**Comment by OmarB97** [comment]
Merged i18n PR. Keeping issue open since we can always add more languages.
